### ISSUE TITLE
获取音乐只能获取前面几首

### ISSUE THREAD

**Issue by Kingsleyrrrr** [perhamer/Find_Love_MusicCloud#2]
https://music.163.com/playlist?id=' + str(playlist_id) 这个只能获取前面几首歌  这个要怎么解决？

**Comment by perhamer** [comment]
网易云做了限制PC端只能看前几首，刚看了下https://interface.music.163.com/weapi/v6/playlist/detail  这个接口还能获取所有歌曲，有空了更一下，或者欢迎提交

**Comment by perhamer** [comment]
代码已经更新了接口
