### ISSUE TITLE
大佬这是啥问题呀

### ISSUE THREAD

**Issue by nidie508** [perhamer/Find_Love_MusicCloud#3]
![QQ图片20200918095514](https://user-images.githubusercontent.com/52956856/93546417-4b7abe00-f995-11ea-8b3c-9a8dd38820d7.png)

**Comment by perhamer** [comment]
ip被ban了

**Comment by nidie508** [comment]
那该怎么解决呢？

**Comment by nidie508** [comment]
> ip被ban了

那该怎么办呢
